In [1]:
import pandas as pd

In [2]:
spi_matches = pd.read_csv("spi_matches.csv")
spi_rankings = pd.read_csv("spi_global_rankings.csv")
spi_intl_rankings = pd.read_csv("spi_global_rankings_intl.csv")

In [3]:
spi_intl_rankings.head(10)

   rank         name    confed   off   def    spi
0     1       Brazil  CONMEBOL  3.11  0.29  92.96
1     2        Spain      UEFA  3.46  0.48  92.54
2     3      Belgium      UEFA  3.06  0.54  89.10
3     4       France      UEFA  2.84  0.46  88.57
4     5      Germany      UEFA  2.96  0.56  87.93
5     6    Argentina  CONMEBOL  2.57  0.49  85.53
6     7      England      UEFA  2.32  0.51  82.36
7     8     Portugal      UEFA  2.38  0.56  81.99
8     9  Netherlands      UEFA  2.55  0.68  81.61
9    10      Uruguay  CONMEBOL  2.30  0.54  81.58

In [4]:
spi_rankings.head(10)

,rank,prev_rank,name,league,off,def,spi
0,1,1,Manchester City,Barclays Premier League,2.92,0.20,93.78
1,2,3,Barcelona,Spanish Primera Division,3.12,0.38,92.41
2,3,4,Real Madrid,Spanish Primera Division,2.99,0.38,91.75
3,4,2,Bayern Munich,German Bundesliga,2.94,0.40,90.93
4,5,6,Juventus,Italy Serie A,2.66,0.29,90.72
5,6,7,Paris Saint-Germain,French Ligue 1,3.09,0.49,90.70
6,7,5,Liverpool,Barclays Premier League,2.66,0.30,90.56
7,8,8,Atletico Madrid,Spanish Primera Division,2.21,0.26,87.34
8,9,9,Chelsea,Barclays Premier League,2.52,0.45,86.66
9,10,10,Tottenham Hotspur,Barclays Premier League,2.42,0.52,84.23

In [5]:
spi_matches.head(10)

,date,league_id,league,team1,team2,spi1,spi2,prob1,prob2,probtie,...,importance1,importance2,score1,score2,xg1,xg2,nsxg1,nsxg2,adj_score1,adj_score2
0,2016-08-12,1843,French Ligue 1,Bastia,Paris Saint-Germain,51.16,85.68,0.0463,0.8380,0.1157,...,32.4,67.7,0.0,1.0,0.97,0.63,0.43,0.45,0.00,1.05
1,2016-08-12,1843,French Ligue 1,AS Monaco,Guingamp,68.85,56.48,0.5714,0.1669,0.2617,...,53.7,22.9,2.0,2.0,2.45,0.77,1.75,0.42,2.10,2.10
2,2016-08-13,2411,Barclays Premier League,Hull City,Leicester City,53.57,66.81,0.3459,0.3621,0.2921,...,38.1,22.2,2.0,1.0,0.85,2.77,0.17,1.25,2.10,1.05
3,2016-08-13,2411,Barclays Premier League,Burnley,Swansea City,58.98,59.74,0.4482,0.2663,0.2854,...,36.5,29.1,0.0,1.0,1.24,1.84,1.71,1.56,0.00,1.05
4,2016-08-13,2411,Barclays Premier League,Middlesbrough,Stoke City,56.32,60.35,0.4380,0.2692,0.2927,...,33.9,32.5,1.0,1.0,1.40,0.55,1.13,1.06,1.05,1.05
5,2016-08-13,2411,Barclays Premier League,Southampton,Watford,69.49,59.33,0.5759,0.1874,0.2367,...,34.1,30.7,1.0,1.0,1.05,0.22,1.52,0.41,1.05,1.05
6,2016-08-13,2411,Barclays Premier League,Everton,Tottenham Hotspur,68.02,73.25,0.3910,0.3401,0.2689,...,31.9,48.0,1.0,1.0,0.73,1.11,0.88,1.81,1.05,1.05
7,2016-08-13,2411,Barclays Premier League,Crystal Palace,West Bromwich Albion,55.19,58.66,0.4214,0.2939,0.2847,...,43.6,34.6,0.0,1.0,1.11,0.68,0.84,1.60,0.00,1.05
8,2016-08-13,1843,French Ligue 1,Bordeaux,St Etienne,62.01,64.92,0.4232,0.2764,0.3004,...,37.9,44.2,3.0,2.0,1.03,1.84,1.10,2.26,3.12,2.10
9,2016-08-13,2411,Barclays Premier League,Manchester City,Sunderland,86.42,53.64,0.8152,0.0525,0.1323,...,73.0,27.0,2.0,1.0,2.14,1.25,1.81,0.92,2.10,1.05

In [6]:
column_headers = list(spi_matches.columns.values)
column_headers

['date',
 'league_id',
 'league',
 'team1',
 'team2',
 'spi1',
 'spi2',
 'prob1',
 'prob2',
 'probtie',
 'proj_score1',
 'proj_score2',
 'importance1',
 'importance2',
 'score1',
 'score2',
 'xg1',
 'xg2',
 'nsxg1',
 'nsxg2',
 'adj_score1',
 'adj_score2']

As it shows, we may be able to use feature engineering to select features for prediction.

In [7]:
from sklearn.preprocessing import LabelEncoder

e = LabelEncoder()
e.fit(spi_matches['team1'])
spi_matches['team1'] = e.transform(spi_matches['team1'])
spi_matches['team2'] = e.transform(spi_matches['team2'])

e.fit(spi_matches['date'])
spi_matches['date'] = e.transform(spi_matches['date'])

In [8]:
spi_matches= spi_matches.drop('league', 1)
spi_matches= spi_matches.drop('probtie', 1)
spi_matches= spi_matches.dropna()

In [9]:
spi_matches.head(10)

,date,league_id,team1,team2,spi1,spi2,prob1,prob2,proj_score1,proj_score2,importance1,importance2,score1,score2,xg1,xg2,nsxg1,nsxg2,adj_score1,adj_score2
0,0,1843,78,473,51.16,85.68,0.0463,0.8380,0.91,2.36,32.4,67.7,0.0,1.0,0.97,0.63,0.43,0.45,0.00,1.05
1,0,1843,16,293,68.85,56.48,0.5714,0.1669,1.82,0.86,53.7,22.9,2.0,2.0,2.45,0.77,1.75,0.42,2.10,2.10
2,1,2411,317,366,53.57,66.81,0.3459,0.3621,1.16,1.24,38.1,22.2,2.0,1.0,0.85,2.77,0.17,1.25,2.10,1.05
3,1,2411,118,610,58.98,59.74,0.4482,0.2663,1.37,1.05,36.5,29.1,0.0,1.0,1.24,1.84,1.71,1.56,0.00,1.05
4,1,2411,404,605,56.32,60.35,0.4380,0.2692,1.30,1.01,33.9,32.5,1.0,1.0,1.40,0.55,1.13,1.06,1.05,1.05
5,1,2411,582,680,69.49,59.33,0.5759,0.1874,1.91,1.05,34.1,30.7,1.0,1.0,1.05,0.22,1.52,0.41,1.05,1.05
6,1,2411,211,633,68.02,73.25,0.3910,0.3401,1.47,1.38,31.9,48.0,1.0,1.0,0.73,1.11,0.88,1.81,1.05,1.05
7,1,2411,179,683,55.19,58.66,0.4214,0.2939,1.35,1.14,43.6,34.6,0.0,1.0,1.11,0.68,0.84,1.60,0.00,1.05
8,1,1843,101,594,62.01,64.92,0.4232,0.2764,1.39,1.14,37.9,44.2,3.0,2.0,1.03,1.84,1.10,2.26,3.12,2.10
9,1,2411,394,608,86.42,53.64,0.8152,0.0525,2.69,0.48,73.0,27.0,2.0,1.0,2.14,1.25,1.81,0.92,2.10,1.05

In [10]:
column_headers = list(spi_matches.columns.values)
column_headers

['date',
 'league_id',
 'team1',
 'team2',
 'spi1',
 'spi2',
 'prob1',
 'prob2',
 'proj_score1',
 'proj_score2',
 'importance1',
 'importance2',
 'score1',
 'score2',
 'xg1',
 'xg2',
 'nsxg1',
 'nsxg2',
 'adj_score1',
 'adj_score2']

In [11]:
decision = ['score1']
features = ['date',
                   'league_id',
                   'team1',
                   'team2',
                   'prob1',
                   'prob2',
                   'spi1',
                   'spi2',
                   'proj_score1',
                   'proj_score2',
                   'importance1',
                   'importance2',
                   'xg1',
                   'xg2']
spi_matches.info

<bound method DataFrame.info of        date  league_id  team1  team2   spi1   spi2   prob1   prob2  \
0         0       1843     78    473  51.16  85.68  0.0463  0.8380
1         0       1843     16    293  68.85  56.48  0.5714  0.1669
2         1       2411    317    366  53.57  66.81  0.3459  0.3621
3         1       2411    118    610  58.98  59.74  0.4482  0.2663
4         1       2411    404    605  56.32  60.35  0.4380  0.2692
5         1       2411    582    680  69.49  59.33  0.5759  0.1874
6         1       2411    211    633  68.02  73.25  0.3910  0.3401
7         1       2411    179    683  55.19  58.66  0.4214  0.2939
8         1       1843    101    594  62.01  64.92  0.4232  0.2764
9         1       2411    394    608  86.42  53.64  0.8152  0.0525
10        1       1843    403    371  54.34  66.10  0.3444  0.3479
11        1       1843    126    379  55.00  47.64  0.4737  0.2401
12        1       1843    410     37  58.82  53.10  0.4939  0.2109
13        1       1843    189    421  55.00  54.90  0.4471  0.2490
14        2       2411     12    395  61.57  80.49  0.2111  0.5461
15        2       1843     17    386  54.87  68.23  0.3584  0.3551
16        2       2411     50    374  82.55  77.44  0.5551  0.2115
17        2       1843    434    601  56.70  53.62  0.4750  0.2298
18        2       1843    399    634  62.62  56.83  0.5033  0.2126
19        3       2411    150    684  80.70  63.27  0.6908  0.1177
20        4       1869    417    457  72.57  56.93  0.5475  0.1897
21        4       1843    386    126  70.32  55.32  0.6106  0.1554
22        4       2411    395    582  81.05  69.22  0.6197  0.1494
23        4       1869    186    197  66.52  62.29  0.5003  0.2260
24        5       2411    605    394  60.42  85.71  0.1278  0.6720
25        5       2411    633    179  73.64  54.21  0.6638  0.1190
26        5       2411    683    211  59.64  67.51  0.3696  0.3491
27        5       2411    680    150  59.57  80.51  0.1955  0.5783
28        5       2411    610    317  60.87  53.47  0.4993  0.2171
29        5       2411    118    374  57.85  78.87  0.2079  0.5520
...     ...        ...    ...    ...    ...    ...     ...     ...
14254   668       1854      7    155  77.67  53.02  0.7422  0.0813
14256   668       1843    101    421  58.49  59.77  0.4225  0.2817
14257   668       1856    110    465  29.67  18.37  0.5509  0.1802
14258   668       1854     55    546  74.47  65.55  0.5456  0.2054
14260   668       1854    360    255  75.70  73.19  0.4861  0.2626
14261   668       2411    582    150  66.17  85.84  0.1972  0.5615
14264   668       1845    615    199  71.60  68.32  0.5070  0.2418
14269   668       5641     72    549  41.40  46.50  0.3773  0.3283
14273   668       1864     96    188  43.02  40.34  0.4619  0.2544
14275   668       1869     60    507  87.25  77.38  0.6392  0.1166
14279   668       1843    399    126  71.09  55.62  0.6657  0.1256
14280   668       1843     16    601  65.91  63.39  0.4791  0.2483
14285   668       2411    374    394  90.64  93.72  0.3758  0.3658
14293   668       1845    498      3  73.75  58.62  0.6575  0.1327
14300   668       1854    422    558  84.24  63.48  0.7126  0.0988
14301   668       5641     64    355  42.02  40.70  0.4473  0.2833
14302   668       1864     85    233  75.69  78.13  0.4150  0.3191
14303   668       1869    565    136  81.34  71.51  0.6404  0.1636
14304   668       1869    207    670  76.51  75.71  0.4695  0.2539
14305   668       1951    181    153  37.81  32.24  0.6086  0.1819
14306   668       1952    628    463  51.03  50.76  0.4334  0.2894
14312   668       5641    527    645  40.77  48.56  0.3466  0.3474
14314   668       1854    585    326  56.52  81.31  0.1666  0.5903
14315   668       1869    651     73  80.05  92.60  0.2220  0.5604
14316   668       1843    473    386  90.04  76.32  0.6563  0.1548
14317   668       1856    466    176  38.74  34.95  0.4985  0.2210
14318   668       1864    487    590  43.49  68.36  0.1945  0.5735
14319   668       5641    616     83  45.13  41.82  0.4236  0.2818
14321   668       5641    499     97  57.04  63.04  0.3823  0.3551
14322   668       1952    494    377  41.73  38.98  0.4852  0.2448

       proj_score1  proj_score2  importance1  importance2  score1  score2  \
0             0.91         2.36         32.4         67.7     0.0     1.0
1             1.82         0.86         53.7         22.9     2.0     2.0
2             1.16         1.24         38.1         22.2     2.0     1.0
3             1.37         1.05         36.5         29.1     0.0     1.0
4             1.30         1.01         33.9         32.5     1.0     1.0
5             1.91         1.05         34.1         30.7     1.0     1.0
6             1.47         1.38         31.9         48.0     1.0     1.0
7             1.35         1.14         43.6         34.6     0.0     1.0
8             1.39         1.14         37.9         44.2     3.0     2.0
9             2.69         0.48         73.0         27.0     2.0     1.0
10            1.18         1.30         26.9         48.7     3.0     2.0
11            1.62         1.11         28.1         28.5     3.0     2.0
12            1.51         0.89         22.5         27.7     1.0     0.0
13            1.40         1.01         29.2         25.6     0.0     1.0
14            1.15         1.78         27.9         58.0     1.0     3.0
15            1.43         1.43         25.2         53.2     0.0     3.0
16            1.91         1.21         62.7         63.9     3.0     4.0
17            1.51         0.99         25.1         28.6     1.0     0.0
18            1.63         0.98         33.4         22.0     0.0     0.0
19            2.23         0.91         67.7         25.5     2.0     1.0
20            1.56         0.70         22.1         31.4     1.0     1.0
21            2.13         0.99         55.3         19.2     2.0     0.0
22            1.85         0.87         61.8         41.6     2.0     0.0
23            1.47         0.79         37.4         38.1     2.0     1.0
24            0.99         1.98         28.9         67.0     1.0     4.0
25            1.94         0.71         44.2         37.5     1.0     0.0
26            1.31         1.30         29.7         27.7     1.0     2.0
27            1.20         1.98         29.4         60.3     1.0     2.0
28            1.41         0.86         29.1         32.4     0.0     2.0
29            1.12         1.79         31.4         56.4     2.0     0.0
...            ...          ...          ...          ...     ...     ...
14254         2.24         0.59         55.5         42.2     3.0     1.0
14256         1.28         0.99         24.7         33.6     3.0     0.0
14257         1.81         0.93         28.5         43.0     4.0     1.0
14258         1.73         0.97         26.3         23.1     0.0     1.0
14260         1.71         1.19         59.8         53.0     1.0     0.0
14261         1.02         1.88         28.5         57.4     0.0     3.0
14264         1.73         1.12         53.1         40.0     1.0     2.0
14269         1.19         1.09          0.9          3.8     2.0     0.0
14273         1.38         0.95         34.2         38.9     1.0     0.0
14275         1.62         0.53         73.1         42.9     1.0     0.0
14279         2.04         0.75         63.9         21.4     2.0     0.0
14280         1.50         1.00         19.7         23.3     1.0     2.0
14285         1.55         1.53        100.0        100.0     0.0     0.0
14293         2.07         0.80         64.7         31.2     6.0     0.0
14300         2.18         0.67         56.9         29.2     2.0     0.0
14301         1.47         1.11         12.2         17.7     0.0     0.0
14302         1.47         1.25        100.0        100.0     1.0     0.0
14303         2.23         1.04         62.5         25.2     2.0     1.0
14304         1.39         0.94         29.1         24.2     3.0     1.0
14305         2.06         1.03         40.1          0.0     2.0     1.0
14306         1.47         1.16         31.9         42.2     2.0     1.0
14312         1.07         1.07          5.1          9.5     0.0     4.0
14314         0.81         1.76         31.3         60.9     1.0     2.0
14315         1.20         2.02         42.1         84.7     1.0     1.0
14316         2.42         1.11         27.6         57.3     5.0     0.0
14317         1.72         1.06         76.1         49.5     1.0     0.0
14318         1.00         1.89         31.8         54.4     4.0     2.0
14319         1.26         0.97          1.1         44.3     3.0     0.0
14321         1.42         1.36        100.0         96.4     2.0     2.0
14322         1.58         1.05         20.2          2.5     2.0     2.0

        xg1   xg2  nsxg1  nsxg2  adj_score1  adj_score2
0      0.97  0.63   0.43   0.45        0.00        1.05
1      2.45  0.77   1.75   0.42        2.10        2.10
2      0.85  2.77   0.17   1.25        2.10        1.05
3      1.24  1.84   1.71   1.56        0.00        1.05
4      1.40  0.55   1.13   1.06        1.05        1.05
5      1.05  0.22   1.52   0.41        1.05        1.05
6      0.73  1.11   0.88   1.81        1.05        1.05
7      1.11  0.68   0.84   1.60        0.00        1.05
8      1.03  1.84   1.10   2.26        3.12        2.10
9      2.14  1.25   1.81   0.92        2.10        1.05
10     2.35  1.87   0.68   1.26        3.15        2.10
11     2.14  2.04   1.88   0.91        3.15        2.10
12     0.80  0.53   0.58   1.28        1.05        0.00
13     0.30  1.17   0.81   0.87        0.00        1.05
14     0.51  2.21   1.11   0.88        1.05        3.15
15     0.37  2.34   1.05   1.39        0.00        2.63
16     1.14  1.84   1.19   1.49        3.15        4.20
17     0.71  1.30   0.33   1.54        1.05        0.00
18     0.38  0.26   0.59   0.81        0.00        0.00
19     1.55  0.55   1.76   0.75        2.10        1.05
20     0.92  0.81   1.40   0.69        1.05        1.05
21     2.92  0.53   1.79   0.52        1.58        0.00
22     1.37  0.70   1.59   1.69        2.10        0.00
23     1.70  0.33   0.48   0.81        2.10        1.05
24     1.38  2.26   0.83   2.05        1.05        3.27
25     2.32  0.40   1.38   0.79        1.05        0.00
26     2.12  1.95   1.76   2.14        1.05        2.10
27     0.76  1.87   0.47   2.04        1.05        2.10
28     1.35  1.94   3.11   0.94        0.00        1.58
29     0.21  1.19   0.33   2.36        2.10        0.00
...     ...   ...    ...    ...         ...         ...
14254  2.82  0.60   2.22   0.85        3.15        1.05
14256  1.59  0.74   0.53   1.85        3.15        0.00
14257  2.93  0.40   1.89   0.60        3.31        1.05
14258  1.82  0.49   2.22   0.82        0.00        1.05
14260  1.48  1.00   1.13   1.06        1.05        0.00
14261  1.72  3.47   0.59   2.53        0.00        2.63
14264  2.43  0.75   3.16   0.61        0.84        2.10
14269  1.11  0.30   1.46   0.90        1.70        0.00
14273  1.09  1.12   1.09   0.83        1.05        0.00
14275  0.57  0.26   1.62   0.56        1.05        0.00
14279  1.47  0.80   1.30   0.80        2.10        0.00
14280  0.39  1.00   0.90   0.71        1.05        1.89
14285  0.42  1.05   0.81   0.62        0.00        0.00
14293  2.87  0.42   1.34   0.51        6.30        0.00
14300  1.63  1.24   1.00   1.15        2.07        0.00
14301  0.49  0.29   1.16   1.26        0.00        0.00
14302  0.81  0.69   0.62   1.06        1.05        0.00
14303  2.00  0.96   1.39   1.46        1.89        1.05
14304  2.71  1.61   2.01   0.99        2.63        1.05
14305  3.18  0.98   1.31   0.81        2.10        1.05
14306  0.87  0.20   0.64   1.23        2.10        1.05
14312  0.85  1.15   0.69   0.69        0.00        3.84
14314  3.05  1.48   1.38   2.36        1.05        2.10
14315  1.37  0.48   1.38   2.46        1.05        1.05
14316  4.81  1.78   1.50   0.70        5.16        0.00
14317  1.05  0.22   2.03   0.39        1.05        0.00
14318  1.01  1.98   1.24   1.77        3.37        2.10
14319  1.76  0.65   0.23   1.30        3.15        0.00
14321  2.08  1.26   1.17   0.72        2.10        1.89
14322  0.50  1.12   0.54   0.87        2.10        2.10

[7010 rows x 20 columns]>

# from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

train, test, train_d, test_d = train_test_split(features,
                                                decision,
                                                test_size = 0.2,
                                                random_state = 14)

cls = RandomForestClassifier()
mdl = cls.fit(train, train_d.values.ravel())

In [12]:
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(spi_matches, test_size=0.2, random_state=42)

In [13]:
from sklearn.ensemble import RandomForestRegressor

clf = RandomForestRegressor(n_jobs=-1, random_state=0)
clf.fit(train_set[features], train_set[decision])

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=-1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [14]:
predicted=clf.predict(test_set[features])
predicted

array([1.2, 1.4, 3.6, ..., 2.4, 0.4, 0.8])

In [15]:
from sklearn.metrics import accuracy_score
T = test_set['score1']
print(accuracy_score(T, predicted))

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets